name: 'version 1'
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node 12.16.2
      uses: actions/setup-node@v2
      with:
        node-version: '12.16.2'
        cache: yarn

    - name: Install dependencies
      run: yarn 
    - name: Prettier-ts
      run: yarn prettier-ts:show --list-different
    - name: Prettier-md
      run: yarn prettier-md:show --list-different
    - name: Prettier-scss
      run: yarn prettier-scss:show --list-different
    - name: Yarn run lint
      run: yarn run ng lint

    - name: Test
      #Service not found: Erro 422 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js 
      run: yarn run ci
    - name: Yarn run demo
      run: yarn run demo:build
